# Model arguments
model_name_or_path: HuggingFaceTB/SmolLM2-360M-Instruct
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2
bf16: true
tf32: true
output_dir: runs/smollm2-360M-r1-countdown

# Dataset arguments
dataset_id_or_path: Jiayi-Pan/Countdown-Tasks-3to4

# Lora Arguments
# No LoRA is used here

# Training arguments
max_steps: 450
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
learning_rate: 5.0e-7 # Use same as in the deepseek math paper (5e-7)
lr_scheduler_type: cosine
warmup_ratio: 0.03

# GRPO specific parameters
beta: 0.001 # Using beta value of 0.001 as in the DeepSeek math paper
max_prompt_length: 256
max_completion_length: 1024
num_generations: 8
use_vllm: true
vllm_device: "cuda:1"
vllm_gpu_memory_utilization: 0.5

# Logging arguments
logging_strategy: steps
logging_steps: 1
report_to:
- tensorboard
- wandb
save_strategy: "steps"
save_steps: 10
seed: 42

# Hugging Face Hub 
push_to_hub: False
  # hub_model_id: if not defined same as output_dir
hub_strategy: every_save 